server:
  port: 8080

spring:
  application:
    name: user-service

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha

data-sources:
  - name: data-base-1
    url: ${DB1_URL:jdbc:postgresql://localhost:5433/db1}
    table: users
    user: ${DB1_USER:testuser}
    password: ${DB1_PASSWORD:testpass}
    mapping:
      id: user_id
      username: login
      name: first_name
      surname: last_name
  - name: data-base-2
    url: ${DB2_URL:jdbc:postgresql://localhost:5434/db2}
    table: user_table
    user: ${DB2_USER:testuser}
    password: ${DB2_PASSWORD:testpass}
    mapping:
      id: ldap_login
      username: ldap_login
      name: name
      surname: surname