version: '3.8'
services:
  db1:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: db1
    ports:
      - "5433:5432"
    volumes:
      - ./sql/db1-init.sql:/docker-entrypoint-initdb.d/init.sql

  db2:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: db2
    ports:
      - "5434:5432"
    volumes:
      - ./sql/db2-init.sql:/docker-entrypoint-initdb.d/init.sql

  task-app:
    build:
      context: ../
      dockerfile: Dockerfile
    image: task-app
    ports:
      - "8080:8080"
    environment:
      DB1_URL: "jdbc:postgresql://db1:5432/db1"
      DB1_USER: "testuser"
      DB1_PASSWORD: "testpass"
      DB2_URL: "jdbc:postgresql://db2:5432/db2"
      DB2_USER: "testuser"
      DB2_PASSWORD: "testpass"
    depends_on:
      - db1
      - db2
